# Generated by Django 3.1.14 on 2022-08-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220821_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_id',
        ),
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
