# Generated by Django 3.1.14 on 2022-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220822_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_present',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
